### ISSUE TITLE
An idea for a highest scoring players display from a player standpoint

### ISSUE THREAD

**Issue by nilejack** [code-differently/24q4-team2#1]
* As a player, I want to see the top 5 scores of all time, listed by player name,  so that I can have bragging rights when I achieve high scores.
*Acceptance criteria: The game should display a high score list that includes player names at the end of each game.

**Comment by anthonydmays** [comment]
I don't think this is going to work without a lot more detail. You may want to come up with a different set of user stories for which you can provide more clarity since games are generally hard.

**Comment by nilejack** [comment]
Good morning again Anthony,
Sorry to send two emails. I just want to send an update of our idea; we
want to clarify the simplicity of our game idea.

   - We want to run our game from the terminal.
   - The back end functionality would implement a number generator using
   either an array list or an array of about twenty numbers(1-20).
   - The game would have two possible player modes using a player class
   where two player objects would live, and  a boolean function would trigger
   whether or not to  generate or 'trigger' the second player.
   - We would use an enum for difficulty modes.
   - The game will have one person , two person, and two person versus
   modes as well.

Similar functionality would be implemented for the TODO app but with
classes for the following; Person, task, time entry, and report.

**Comment by anthonydmays** [comment]
Here's how you can reshape your user stories:

#1: "As a player, I want to play a game where I have to guess a number between a given range in the least number of guesses, so that I can casually pass the time."

#2: "As a player, I want to play with another player by competing for the least number of guesses so that I can enjoy the game with my friends."

#3: "As a player, I want to see the top 10 scores all time by player name so that I can have bragging when I achieve high scores."

Consider adopting these users stories which I believe are much more clear and manageable within the required timeline. If you take these, then make sure to update the `Issue` titles appropriately.

**Comment by nilejack** [comment]
Okay, thank you! We'll have the stories updated by 1pm today.

Thanks again
